# Generated by Django 2.2.4 on 2019-08-24 15:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestCode', models.CharField(max_length=80)),
                ('userEmail', models.CharField(blank=True, max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(blank=True, max_length=100)),
                ('userEmail', models.CharField(max_length=100)),
                ('fileName', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='PROCESSING', max_length=50)),
                ('code', models.CharField(default=uuid.uuid4, max_length=80, unique=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('totalTime', models.TimeField(blank=True, default=None, null=True)),
                ('tools', models.ManyToManyField(through='request_records.RequestInfo', to='tools.Tool')),
            ],
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request_records.RequestRecord'),
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Tool'),
        ),
    ]
