# Generated by Django 2.2.4 on 2019-08-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrecord',
            name='file',
            field=models.FileField(default=(), upload_to='files'),
            preserve_default=False,
        ),
    ]
