# Generated by Django 2.2.4 on 2019-08-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_records', '0002_requestrecord_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrecord',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='files'),
        ),
    ]
