# Generated by Django 2.2.4 on 2019-09-02 15:26

from django.db import migrations, models
import request_records.models


class Migration(migrations.Migration):

    dependencies = [
        ('request_records', '0003_auto_20190826_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestrecord',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=request_records.models.get_upload_path),
        ),
    ]
