# Generated by Django 2.2.4 on 2019-09-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_records', '0004_auto_20190902_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='endDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='status',
            field=models.CharField(default='PROCESSING', max_length=50),
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='totalTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
